name: fva_songs
description: "Application de chants et cantiques pour le culte - FVA Songs"
publish_to: 'none'
version: 0.1.1+2

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  flutter_riverpod: ^2.6.1
  go_router: ^15.1.2
  google_fonts: ^6.2.1
  firebase_core: ^3.15.1
  firebase_auth: ^5.6.2
  cloud_firestore: ^5.6.11
  shared_preferences: ^2.5.3
  flutter_native_splash: ^2.4.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  mocktail: ^1.0.5
  fake_cloud_firestore: ^3.1.0
  firebase_auth_mocks: ^0.14.2

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/branding/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/branding/app_icon.png
  min_sdk_android: 21
  adaptive_icon_background: "#E6ECF2"
  adaptive_icon_foreground: assets/branding/app_icon.png
  adaptive_icon_foreground_inset: 16
  remove_alpha_ios: true
  background_color_ios: "#E6ECF2"

flutter_native_splash:
  color: "#E6ECF2"
  image: assets/branding/app_icon.png
  android: true
  ios: true
  android_12:
    color: "#E6ECF2"
    image: assets/branding/app_icon.png
  web: false
